"""skill_manager：A2 Skill 外骨骼（registry / policy / invoker；安装与调用见 Sprint 7.3+）。"""

from offline_companion.shared.types import PurposeType
from offline_companion.shell.skill_manager.invoker import SkillInvoker, SkillProcess
from offline_companion.shell.skill_manager.manifest import SkillEntrypoint, SkillManifest
from offline_companion.shell.skill_manager.policy import (
    SkillPolicyResult,
    check_read_context,
    evaluate_skill_policy,
    require_skill_allowed,
)
from offline_companion.shell.skill_manager.registry import (
    MANIFEST_TYPE_PLUGIN,
    MANIFEST_TYPE_SKILL,
    MANIFEST_TYPE_TOOL,
    compare_versions,
    installed_extensions_dir,
    load_installed_manifests,
    load_manifest_file,
    manifest_type_from_dict,
    parse_market_id,
    parse_pep440_version,
    skill_install_dir,
    validate_manifest_dict,
)
from offline_companion.shell.skill_manager.seccomp import (
    SECCOMP_PROFILE_COMPUTE,
    SECCOMP_PROFILE_FILE_IO,
    SECCOMP_PROFILE_NETWORK,
    SeccompLoadResult,
    load_profile,
    seccomp_runtime_supported,
    select_seccomp_profile,
)
from offline_companion.shell.skill_manager.supply_chain import (
    audit_supply_chain_failure,
    bundled_hash_manifest_path,
    host_trust_anchor_path,
    register_bundled_trust_anchor,
    sbom_path,
    sha256_file,
    verify_bundled_skill_integrity,
    verify_requirements_hashes,
    verify_supply_chain,
    write_sbom,
)

__all__ = [
    "MANIFEST_TYPE_PLUGIN",
    "MANIFEST_TYPE_SKILL",
    "MANIFEST_TYPE_TOOL",
    "SECCOMP_PROFILE_COMPUTE",
    "SECCOMP_PROFILE_FILE_IO",
    "SECCOMP_PROFILE_NETWORK",
    "PurposeType",
    "SeccompLoadResult",
    "SkillEntrypoint",
    "SkillInvoker",
    "SkillManifest",
    "SkillPolicyResult",
    "SkillProcess",
    "audit_supply_chain_failure",
    "bundled_hash_manifest_path",
    "check_read_context",
    "compare_versions",
    "evaluate_skill_policy",
    "host_trust_anchor_path",
    "installed_extensions_dir",
    "load_installed_manifests",
    "load_manifest_file",
    "load_profile",
    "manifest_type_from_dict",
    "parse_market_id",
    "parse_pep440_version",
    "register_bundled_trust_anchor",
    "require_skill_allowed",
    "sbom_path",
    "seccomp_runtime_supported",
    "select_seccomp_profile",
    "sha256_file",
    "skill_install_dir",
    "validate_manifest_dict",
    "verify_bundled_skill_integrity",
    "verify_requirements_hashes",
    "verify_supply_chain",
    "write_sbom",
]
